# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'charles.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(459, 382)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(380, 0, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.us_name = QtWidgets.QLineEdit(self.centralwidget)
        self.us_name.setGeometry(QtCore.QRect(110, 10, 141, 21))
        self.us_name.setObjectName("us_name")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(50, 10, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.all_messages = QtWidgets.QTextBrowser(self.centralwidget)
        self.all_messages.setGeometry(QtCore.QRect(50, 40, 371, 181))
        self.all_messages.setObjectName("all_messages")
        self.us_text = QtWidgets.QTextEdit(self.centralwidget)
        self.us_text.setGeometry(QtCore.QRect(50, 250, 371, 51))
        self.us_text.setObjectName("us_text")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(50, 230, 141, 16))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.send = QtWidgets.QPushButton(self.centralwidget)
        self.send.setGeometry(QtCore.QRect(50, 310, 371, 41))
        self.send.setObjectName("send")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Charles v1.0.0"))
        self.us_name.setPlaceholderText(_translate("MainWindow", "Введите имя"))
        self.label_3.setText(_translate("MainWindow", "От кого"))
        self.us_text.setPlaceholderText(_translate("MainWindow", "Написать сообщение"))
        self.label_4.setText(_translate("MainWindow", "Новое Сообщение:"))
        self.send.setText(_translate("MainWindow", "< Отправить > "))
