# Generated by Django 3.0.4 on 2020-03-31 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'verbose_name': 'Заметку', 'verbose_name_plural': 'Заметки'},
        ),
        migrations.AddField(
            model_name='note',
            name='satus_note',
            field=models.CharField(choices=[('0', 'Не выполнено'), ('1', 'В процессе'), ('3', 'Выполнено')], default='1', max_length=20, verbose_name='Статус'),
        ),
    ]
