# Generated by Django 3.0.4 on 2020-03-31 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_auto_20200331_1630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='satus_note',
        ),
        migrations.AddField(
            model_name='note',
            name='status_note',
            field=models.CharField(choices=[('0', 'Не выполнено'), ('1', 'В процессе'), ('2', 'Выполнено')], default='1', max_length=20, verbose_name='Статус'),
        ),
    ]
