# Generated by Django 3.0.4 on 2020-08-02 16:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название статьи')),
                ('text', models.TextField(verbose_name='Текст статьи')),
                ('date', models.DateField(default=datetime.datetime.now, verbose_name='Дата публикации')),
            ],
        ),
        migrations.CreateModel(
            name='UserListFB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_fb', models.CharField(max_length=50, verbose_name='Автор')),
                ('email_fb', models.CharField(max_length=100, verbose_name='Email')),
                ('text_fb', models.TextField(max_length=250, verbose_name='Текст статьи')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=50, verbose_name='Автор')),
                ('text_comment', models.TextField(max_length=250, verbose_name='Текст статьи')),
                ('date_comment', models.DateField(default=datetime.datetime.now, verbose_name='Дата комментария')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Publication')),
            ],
        ),
    ]
