# Generated by Django 3.0.4 on 2020-08-03 07:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200803_0710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date_comment',
            field=models.DateField(default=datetime.datetime(2020, 8, 3, 7, 11, 59, 545251), verbose_name='Дата комментария'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 8, 3, 7, 11, 59, 544572), verbose_name='Дата публикации'),
        ),
    ]
