# Generated by Django 3.0.4 on 2020-08-03 07:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200803_0721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date_comment',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 3, 7, 26, 19, 823616), verbose_name='Дата комментария'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 3, 7, 26, 19, 822572), verbose_name='Дата публикации'),
        ),
    ]
