# Generated by Django 3.0.4 on 2020-08-06 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Publication',
            new_name='Users',
        ),
    ]
