# Generated by Django 3.0.4 on 2020-08-06 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200806_1239'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users_auth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pasword', models.CharField(max_length=100, verbose_name='Пароль')),
                ('email', models.TextField(verbose_name='Email')),
            ],
        ),
        migrations.RenameModel(
            old_name='Users',
            new_name='Users_reg',
        ),
    ]
