# Generated by Django 3.0.4 on 2020-08-06 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200806_1306'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users_auth',
        ),
        migrations.RenameField(
            model_name='users_reg',
            old_name='pasword',
            new_name='password',
        ),
    ]
